### ISSUE TITLE
InflateException with MVVMCross

### ISSUE THREAD

**Issue by dot-ly** [mikescandy/Calligraphy-xamarin#1]
Hello,

First off, this is a great Library. Very handy! 

I'm having issues getting it to work with MvvmCross, I get the following error 

[Calligraphy] Exception of type 'Android.Views.InflateException' was thrown.

Weird thing is that it works on the splashscreen view, but now the firstview that MvvmCross creates. 

Any ideas?

**Comment by mikescandy** [comment]
Thanks!
Haven't tried this on MvvmCross, I'll fire up a project and have a look..

**Comment by dot-ly** [comment]
Hi Mike, 

Looking into this more, it's not really an issue with the Library itself, it's more about how both MVVMCross and Calligraphy handle the view inflation. 

http://stackoverflow.com/questions/28950588/injection-of-default-typeface
