### ISSUE TITLE
Update binding

### ISSUE THREAD

**Issue by melanke** [mikescandy/Calligraphy-xamarin#3]
Could you please update to fix this issue:
https://github.com/chrisjenx/Calligraphy/issues/155

Thanks

**Comment by mikescandy** [comment]
Hi @melanke, please check the branch updateToLatest. It should build and the sample app should work, although it need a massive cleanup. Should be up to date with the latest version.

**Comment by mikescandy** [comment]
I replaced my ported code with a simpler binding. Using it myself, seems to work ok. If it's ok with you, I would close this issue.

**Comment by melanke** [comment]
Sure! Actually, I'm done with Xamarin haha
